//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporate_Custoer_Tbl
    {
        public int Corporate_Custoer_Id { get; set; }
        public string Corporate_Custoer_Name { get; set; }
    }
}
