//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Minutes_Details_Tbl
    {
        public int Meeting_Minutes_Details_Id { get; set; }
        public string Products_Service_Name { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Quantity { get; set; }
    }
}
